resources:

- name: git-play-with-timer-resource
  type: git
  source:
    uri: git@github.com:suhlig/play-with-timer-resource.git
    uri: https://github.com/suhlig/play-with-timer-resource.git
    branch: master

- name: time-monday
  type: time
  source:
    start: 12:01 AM -0000
    stop:  11:59 PM -0000
    days:  [ Monday ]

- name: time-tuesday
  type: time
  source:
    start: 12:01 AM -0000
    stop:  11:59 PM -0000
    days:  [ Tuesday ]

jobs:
- name: run-tests-on-monday
  plan:
  - get: time-monday
    trigger: true
  - get: git-play-with-timer-resource
    trigger: false
  - task: run-tests
    config:
      run:
        path: 'echo'
        args: ['Monday morning feels so bad, everybody seems to nag me']

- name: run-tests-on-tuesday
  plan:
  - get: time-tuesday
    trigger: true
  - get: git-play-with-timer-resource
    trigger: false
  - task: run-tests
    config:
      run:
        path: 'echo'
        args: ['Come on Tuesday I feel better, even my old man looks good']
