resources:

- name: git-play-with-timer-resource
  type: git
  source:
    uri: git@github.com:suhlig/play-with-timer-resource.git
    uri: https://github.com/suhlig/play-with-timer-resource.git
    branch: master

- name: timer
  type: time
  source:
    start: 12:00 AM -0700
    stop: 1:00 AM -0700

jobs:
- name: run-tests
  plan:
  - get: timer
    trigger: true
  - get: git-play-with-timer-resource
    trigger: false
  - task: run-tests
    config:
      run:
        path: 'echo'
        args: ['OK!']
